import { ReactElement } from "react";
import MainLayout from "@/components/main-layout";
import { NextPageWithLayout } from "../../../_app";
import Head from "next/head";
import style from "@/styles/modules/build-info.module.scss";
import { useRouter } from "next/router";
import { GetStaticPaths, GetStaticPropsContext } from "next";
import {
  fetchNewBySlug,
  fetchNewCategories,
  fetchNewsForHome,
} from "lib/api/news";
import { INewCategory, INews } from "lib/types";
import { ParsedUrlQuery } from "querystring";
import useSWR from "swr";
import Breadcrums from "@/components/common/breadcrums";
import { newsDetail, newsDetail2 } from "@/constants/images";
import Image from "next/image";
import NewRelated from "@/components/news/news-related";

interface IParams extends ParsedUrlQuery {
  slug: string;
}

const NewDetailPage: NextPageWithLayout = () => {
  const { query } = useRouter();
  const { data, error } = useSWR(query.slug, fetchNewBySlug);
  const news = data;
  const breadcrumbs = [
    {
      title: "Thông tin xây dựng",
      slug: "thong-tin-xay-dung",
    },
    {
      slug: "",
      title: news?.category.name || "",
    },
    {
      title: news?.title || "",
      slug: "",
    },
  ];
  return (
    <>
      <Head>
        <title>{news?.title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={style.NewsMain}>
        <Breadcrums breadcrumbs={breadcrumbs} />
        <div className={style.Build_News_Content}>
          <h1 className={style.Build_News_Content_Title}>{news?.title}</h1>
          <div className={style.Build_News_Content_Date}>{news?.date}</div>
          <div className={style.Build_News_Content_Content}>
            <div style={{ margin: "auto", textAlign: "center" }}>
              Nullam scelerisque alias nemo repudiandae cupidatat, habitasse
              adipisicing, hendrerit, aliquet, fusce metus dolor libero? Ab,
              viverra dictumst penatibus odio, sodales magnam provident non
              adipiscing adipisicing, laudantium iaculis pede, mauris tortor,
              odio orci! Laoreet officiis, hymenaeos ultrices, integer ligula
              praesent nobis pellentesque fusce magna porttitor adipiscing neque
              orci purus distinctio distinctio diamlorem elit congue omnis
              laborum quis, commodi aliquip. Dicta quod? Arcu atque lacinia
              perspiciatis molestiae suspendisse quibusdam litora purus
              consequatur accusamus natoque. Cum tenetur molestie aliquip etiam
              malesuada? Pulvinar mauris, gravida, pellentesque sapien sem, id,
              dolorem! Hic eligendi ligula distinctio, luctus ipsam numquam
              varius architecto magna! Pulvinar maxime massa iste.
            </div>
            <div style={{ margin: "32px 0" }}>
              <Image src={newsDetail} alt="" />
            </div>
            <div>
              Nullam scelerisque alias nemo repudiandae cupidatat, habitasse
              adipisicing, hendrerit, aliquet, fusce metus dolor libero? Ab,
              viverra dictumst penatibus odio, sodales magnam provident non
              adipiscing adipisicing, laudantium iaculis pede, mauris tortor,
              odio orci! Laoreet officiis, hymenaeos ultrices, integer ligula
              praesent nobis pellentesque fusce magna porttitor adipiscing neque
              orci purus distinctio distinctio diamlorem elit congue omnis
              laborum quis, commodi aliquip. Dicta quod? Arcu atque lacinia
              perspiciatis molestiae suspendisse quibusdam litora purus
              consequatur accusamus natoque. Cum tenetur molestie aliquip etiam
              malesuada? Pulvinar mauris, gravida, pellentesque sapien sem, id,
              dolorem! Hic eligendi ligula distinctio, luctus ipsam numquam
              varius architecto magna! Pulvinar maxime massa iste.Nullam
              scelerisque alias nemo repudiandae cupidatat, habitasse
              adipisicing, hendrerit, aliquet, fusce metus dolor libero? Ab,
              viverra dictumst penatibus odio, sodales magnam provident non
              adipiscing adipisicing, laudantium iaculis pede, mauris tortor,
              odio orci! Laoreet officiis, hymenaeos ultrices, integer ligula
              praesent nobis pellentesque fusce magna porttitor adipiscing neque
              orci purus distinctio distinctio diamlorem elit congue omnis
              laborum quis, commodi aliquip. Dicta quod? Arcu atque lacinia
              perspiciatis molestiae suspendisse quibusdam litora purus
              consequatur accusamus natoque. Cum tenetur molestie aliquip etiam
              malesuada? Pulvinar mauris, gravida, pellentesque sapien sem, id,
              dolorem! Hic eligendi ligula distinctio, luctus ipsam numquam
              varius architecto magna! Pulvinar maxime massa iste.Nullam
              scelerisque alias nemo repudiandae cupidatat, habitasse
              adipisicing, hendrerit, aliquet, fusce metus dolor libero? Ab,
              viverra dictumst penatibus odio, sodales magnam provident non
              adipiscing adipisicing, laudantium iaculis pede, mauris tortor,
              odio orci! Laoreet officiis, hymenaeos ultrices, integer ligula
              praesent nobis pellentesque fusce magna porttitor adipiscing neque
              orci purus distinctio distinctio diamlorem elit congue omnis
              laborum quis, commodi aliquip. Dicta quod? Arcu atque lacinia
              perspiciatis molestiae suspendisse quibusdam litora purus
              consequatur accusamus natoque. Cum tenetur molestie aliquip etiam
              malesuada? Pulvinar mauris, gravida, pellentesque sapien sem, id,
              dolorem! Hic eligendi ligula distinctio, luctus ipsam numquam
              varius architecto magna! Pulvinar maxime massa iste.Nullam
              scelerisque alias nemo repudiandae cupidatat, habitasse
              adipisicing, hendrerit, aliquet, fusce metus dolor libero? Ab,
              viverra dictumst penatibus odio, sodales magnam provident non
              adipiscing adipisicing, laudantium iaculis pede, mauris tortor,
              odio orci! Laoreet officiis, hymenaeos ultrices, integer ligula
              praesent nobis pellentesque fusce magna porttitor adipiscing neque
              orci purus distinctio distinctio diamlorem elit congue omnis
              laborum quis, commodi aliquip. Dicta quod? Arcu atque lacinia
              perspiciatis molestiae suspendisse quibusdam litora purus
              consequatur accusamus natoque. Cum tenetur molestie aliquip etiam
              malesuada? Pulvinar mauris, gravida, pellentesque sapien sem, id,
              dolorem! Hic eligendi ligula distinctio, luctus ipsam numquam
              varius architecto magna! Pulvinar maxime massa iste.
            </div>
            <div style={{ margin: "32px 0" }}>
              <Image src={newsDetail2} alt="" />
            </div>
          </div>
        </div>
        <NewRelated />
      </div>
    </>
  );
};
export const getStaticPaths: GetStaticPaths = async () => {
  const cates = await fetchNewCategories("/news");
  const newss = await fetchNewsForHome("/news");

  // Get the paths we want to pre-render based on posts
  let paths: { params: { cslug: string; slug: string } }[] = [];
  cates.forEach((cate) => {
    const cNews = newss.filter((n) => n.category.id === cate.id);
    cNews.forEach((n) => {
      paths.push({ params: { cslug: cate.slug, slug: n.slug } });
    });
  });

  return {
    paths,
    fallback: "blocking", //indicates the type of fallback
  };
};

export async function getStaticProps(context: GetStaticPropsContext) {
  // `getStaticProps` is executed on the server side.
  const { slug } = context.params as IParams;

  const news = await fetchNewBySlug(slug);
  if (!news) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      news,
    },
  };
}

NewDetailPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default NewDetailPage;
