import { ReactElement, useState, useEffect } from "react";
import { NextPageWithLayout } from "../../_app";
import Head from "next/head";
import style from "@/styles/modules/supplier.module.scss";
import { Row, Col, Select } from "antd";

import SupplierLayout from "@/components/layouts/supplier-layout";
import ProductCategories from "@/components/supplier/product-categories";
import { searchIcon, suppAbout } from "@/constants/images";
import Image from "next/image";
import { useRouter } from "next/router";
import ProductGroups from "@/components/supplier/product-groups";
import ProductRetails from "@/components/supplier/product-retail";

const SupplierAboutPage: NextPageWithLayout = () => {
  const [tabSelected, setTabSelected] = useState("group");
  const [currentPath, setcurrentPath] = useState("");
  const router = useRouter();
  const { query } = router;
  console.log(router);

  useEffect(() => {
    const { tab, slug } = query;
    setTabSelected(tab === "san-pham-le" ? "product" : "group");
    if (slug) {
      const cPath = router.pathname.replace("[slug]", slug.toString());
      setcurrentPath(cPath);
    }
  }, [query]);

  return (
    <>
      <Head>
        <title>Giới thiệu chung</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div style={{ padding: 16, fontWeight: 400, lineHeight: "150%" }}>
        <b>Trung tâm vlxd Thống Nhất </b> là thành viên của Đồng tâm group, Sản
        xuất và kinh doanh các sản phẩm vật liệu xây dựng và trang trí nội thất;
        kinh doanh bất động sản, đầu tư, khai thác cảng biển, xây dựng và cho
        thuê đất trong khu công nghiệp, cho thuê nhà xưởng, đầu tư liên doanh,
        liên kết.
        <div style={{ margin: "24px 0" }}>
          <Image src={suppAbout} alt="" />
        </div>
        <div>
          Bibendum, tempus tristique felis quibusdam sint! Sequi sapiente, eos.
          Nostra minima nemo quis vehicula mollit, parturient mi provident
          torquent at laboriosam, eros voluptates quisquam! Risus dolorum
          molestias eros fusce facilisi vel cupidatat pulvinar totam fames quod
          impedit maxime vivamus massa! Nostrum repellat, per cupiditate
          ullamcorper laboriosam, ullam? Repellendus. Eos porta molestias
          accusamus! Adipisicing. Corrupti eos modi facilisi occaecati eleifend
          nibh! Tellus eiusmod litora eiusmod ex voluptas, porro omnis cubilia
          ipsum, tellus justo? Fuga pede ridiculus, pariatur voluptas! Sodales,
          penatibus quae, dictumst interdum minus magnam, morbi provident.
          Doloribus incididunt! Aut ex, voluptas dictum, consequatur suspendisse
          laboriosam sed! Eos, dolore interdum, ligula.
        </div>
      </div>
    </>
  );
};
SupplierAboutPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <SupplierLayout>{page}</SupplierLayout>
    </>
  );
};
export default SupplierAboutPage;
