import { ReactElement, useState, useEffect } from "react";
import { NextPageWithLayout } from "../../_app";
import Head from "next/head";
import style from "@/styles/modules/supplier.module.scss";
import { Row, Col, Select } from "antd";

import SupplierLayout from "@/components/layouts/supplier-layout";
import ProductCategories from "@/components/supplier/product-categories";
import { searchIcon } from "@/constants/images";
import Image from "next/image";
import { useRouter } from "next/router";
import ProductGroups from "@/components/supplier/product-groups";
import ProductRetails from "@/components/supplier/product-retail";

const SupplierAboutPage: NextPageWithLayout = () => {
  const [tabSelected, setTabSelected] = useState("group");
  const [currentPath, setcurrentPath] = useState("");
  const router = useRouter();
  const { query } = router;
  console.log(router);

  useEffect(() => {
    const { tab, slug } = query;
    setTabSelected(tab === "san-pham-le" ? "product" : "group");
    if (slug) {
      const cPath = router.pathname.replace("[slug]", slug.toString());
      setcurrentPath(cPath);
    }
  }, [query]);

  return (
    <>
      <Head>
        <title>Giới thiệu chung</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </>
  );
};
SupplierAboutPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <SupplierLayout>{page}</SupplierLayout>
    </>
  );
};
export default SupplierAboutPage;
