import { ReactElement } from "react";
import { NextPageWithLayout } from "../../_app";
import Head from "next/head";
import style from "@/styles/modules/supplier.module.scss";
import { bgProject, projectAvata } from "@/constants/images";
import SupplierChart from "@/components/supplier/supplier-chart";
import SupplierTopViewChart from "@/components/supplier/top-view-chart";
import { Row, Col } from "antd";
import suppliers from "../../../data/suppliers.json";
import ProductCard from "@/components/products/product-card";
import ProjectCard from "@/components/project/project-card";
import { IProject } from "lib/types";
import SupplierLayout from "@/components/layouts/supplier-layout";

const projects: IProject[] = [
  {
    id: 1,
    name: "Vinhome Ocean Park",
    des: "Quos aliquip repudiandae condimentum congue anim vitae voluptates velit aliquet fugit beatae.",
    owner: "Vinhomes",
    avata: projectAvata,
    image: bgProject,
  },
  {
    id: 2,
    name: "Vinhomes The Empire",
    des: "Quos aliquip repudiandae condimentum congue anim vitae voluptates velit aliquet fugit beatae.",
    owner: "Vinhomes",
    avata: projectAvata,
    image: bgProject,
  },
  {
    id: 3,
    name: "Vinhomes Wonder Park",
    des: "Quos aliquip repudiandae condimentum congue anim vitae voluptates velit aliquet fugit beatae.",
    owner: "Vinhomes",
    avata: projectAvata,
    image: bgProject,
  },
  {
    id: 4,
    name: "Vinhomes Green Hạ Long",
    des: "Quos aliquip repudiandae condimentum congue anim vitae voluptates velit aliquet fugit beatae.",
    owner: "Vinhomes",
    avata: projectAvata,
    image: bgProject,
  },
];

const SupplierPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Đại lý</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Row style={{ width: "100%" }}>
        <Col md={24} lg={8}>
          <div className={style.supplierHeaderContent}>
            <SupplierChart />
          </div>
        </Col>
        <Col md={24} lg={16}>
          <div className={style.supplierTopViewChart_Wapper}>
            <SupplierTopViewChart />
          </div>
        </Col>
      </Row>
      <section className={style.sectionTopViewProduct}>
        <div className={style.SectionTopViewTitle}>
          Nhóm sản phẩm được xem nhiều nhất
        </div>
        <div className="products-result">
          <Row style={{ justifyContent: "center" }}>
            {suppliers.map((supplier) => {
              return (
                <Col
                  key={supplier.id}
                  style={{ padding: 12 }}
                  sm={24}
                  md={12}
                  lg={6}
                >
                  <ProductCard supplier={supplier} />
                </Col>
              );
            })}
          </Row>
        </div>
      </section>
      <section className={style.SectionProjects}>
        <div className={style.SectionProjects_Title}>
          Dự án tham gia của nhà cung cấp
        </div>
        <Row gutter={[8, 16]}>
          {projects.map((project) => {
            return (
              <Col
                key={project.id}
                style={{ padding: 12 }}
                sm={24}
                md={12}
                lg={6}
              >
                <ProjectCard project={project} />
              </Col>
            );
          })}
        </Row>
      </section>
    </>
  );
};
SupplierPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <SupplierLayout>{page}</SupplierLayout>
    </>
  );
};
export default SupplierPage;
