import { ReactElement } from "react";
import { NextPageWithLayout } from "../../_app";
import Head from "next/head";
import style from "@/styles/modules/supplier.module.scss";
import { bgProject, projectAvata } from "@/constants/images";
import Link from "next/link";
import SupplierChart from "@/components/supplier/supplier-chart";
import SupplierTopViewChart from "@/components/supplier/top-view-chart";
import { Row, Col } from "antd";
import { IProject } from "types";
import SupplierLayout from "@/components/layouts/supplier-layout";
import ProductCategories from "@/components/supplier/product-categories";

const projects: IProject[] = [
  {
    id: 1,
    name: "Vinhome Ocean Park",
    des: "Quos aliquip repudiandae condimentum congue anim vitae voluptates velit aliquet fugit beatae.",
    owner: "Vinhomes",
    avata: projectAvata,
    image: bgProject,
  },
  {
    id: 2,
    name: "Vinhomes The Empire",
    des: "Quos aliquip repudiandae condimentum congue anim vitae voluptates velit aliquet fugit beatae.",
    owner: "Vinhomes",
    avata: projectAvata,
    image: bgProject,
  },
  {
    id: 3,
    name: "Vinhomes Wonder Park",
    des: "Quos aliquip repudiandae condimentum congue anim vitae voluptates velit aliquet fugit beatae.",
    owner: "Vinhomes",
    avata: projectAvata,
    image: bgProject,
  },
  {
    id: 4,
    name: "Vinhomes Green Hạ Long",
    des: "Quos aliquip repudiandae condimentum congue anim vitae voluptates velit aliquet fugit beatae.",
    owner: "Vinhomes",
    avata: projectAvata,
    image: bgProject,
  },
];

const SupplierProductsPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Tất cả sản phẩm</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Row gutter={32}>
        <Col md={6} className={style.Supp_products_Categories}>
          <ProductCategories />
        </Col>
        <Col md={18}></Col>
      </Row>
    </>
  );
};
SupplierProductsPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <SupplierLayout>{page}</SupplierLayout>
    </>
  );
};
export default SupplierProductsPage;
