import SearchInput from "@/components/common/searchInput";
import MainLayout from "@/components/main-layout";
import style from "@/styles/modules/legal.module.scss";
import Head from "next/head";
import { ReactElement } from "react";
import { NextPageWithLayout } from "../_app";
const EmptyPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Văn bản pháp lý</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col px-5 py-0 lg:px-[120px] lg:py-[60px] justify-center items-center lg:items-start gap-6 lg:gap-10 mx-0 my-6 lg:m-0">
        <div className="flex flex-col items-center w-full px-5 py-0 lg:px-[103px] lg:py-0">
          <div className="flex flex-col items-start gap-4 bg-[#f8f9ff] w-full rounded-[8px] p-6 lg:rounded-[4px] lg:p-8">
            <div className="not-italic font-normal text-[20px] mb-4">
              Tìm văn bản pháp lý
            </div>
            <div className="w-full">
              <SearchInput />
            </div>
          </div>
        </div>
        <div className="flex flex-col items-center p-0"></div>
      </div>
    </>
  );
};
EmptyPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default EmptyPage;
