import { ReactElement } from "react";
import MainLayout from "@/components/main-layout";
import { NextPageWithLayout } from "../_app";
import Head from "next/head";
import style from "@/styles/modules/legal.module.scss";
import SearchInput from "@/components/common/searchInput";
const EmptyPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Văn bản pháp lý</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={style.Main}>
        <div className={style.Main_SearchSection}>
          <div className={style.Main_SearchSection_Card}>
            <div className={style.Main_SearchSection_Card_Title}>
              Tìm văn bản pháp lý
            </div>
            <div className={style.Main_SearchSection_Card_Search}>
              <SearchInput />
            </div>
          </div>
        </div>
        <div className={style.Main_Categories}></div>
      </div>
    </>
  );
};
EmptyPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default EmptyPage;
