import { ReactElement } from "react";
import MainLayout from "@/components/main-layout";
import { NextPageWithLayout } from "../_app";
import Head from "next/head";
const EmptyPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Văn bản pháp lý</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="main-content">
        <h1>Văn bản pháp lý</h1>
      </div>
    </>
  );
};
EmptyPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default EmptyPage;
