import { ReactElement } from "react";
import MainLayout from "@/components/main-layout";
import { NextPageWithLayout } from "../_app";
import Head from "next/head";
import CardRootCategory from "@/components/products/CardRootCategory";
import { Col, Row, Skeleton } from "antd";
import useSWR from "swr";
import { ICategory } from "lib/types";
import { fetchCategories, fetchChildsCategories } from "lib/api/category";
type Props = {
  categories: ICategory[];
};
const SanPham: NextPageWithLayout<Props> = (props: Props) => {
  const {
    data: categories,
    error,
    isLoading,
  } = useSWR<ICategory[], []>("0", fetchCategories, {
    fallbackData: props.categories,
  });
  const roots = categories?.filter((c) => c.parentId === "0");
  if (error) {
    return <div>error</div>;
  }
  return (
    <>
      <Head>
        <title>Nhóm sản phẩm</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="main-content">
        <Row gutter={[32, 32]}>
          {isLoading && categories === undefined
            ? Array(8)
                .fill(0)
                .map((_, i) => (
                  <Col key={i} md={24} lg={12}>
                    {" "}
                    <Skeleton active />
                  </Col>
                ))
            : null}
          {roots?.map((c) => (
            <Col key={c.id} md={24} lg={12}>
              <CardRootCategory
                children={categories?.filter((c) => c.parentId === c.parentId)}
                category={c}
              />
            </Col>
          ))}
        </Row>
      </div>
    </>
  );
};
export async function getStaticProps() {
  const categories = await fetchCategories("8974829147");
  return {
    props: {
      categories: categories,
    },
  };
}

SanPham.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default SanPham;
