import { ReactElement } from "react";
import MainLayout from "@/components/main-layout";
import { NextPageWithLayout } from "../_app";
import Head from "next/head";
import CardRootCategory from "@/components/products/CardRootCategory";
import { Col, Row } from "antd";
import useSWR from "swr";
import { ICategory } from "lib/types";
import { fetchCategories, fetchChildsCategories } from "lib/api/category";
type Props = {
  categories: ICategory[];
};

const SanPham: NextPageWithLayout<Props> = (props: Props) => {
  const { data: roots, error } = useSWR<ICategory[], []>(
    "0",
    fetchChildsCategories,
    {
      fallbackData: props.categories,
    }
  );
  if (error) {
    return <div>error</div>;
  }
  return (
    <>
      <Head>
        <title>Empty</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="main-content">
        <Row gutter={[32, 32]}>
          {roots?.map((c) => (
            <Col key={c.id} md={24} lg={12}>
              <CardRootCategory category={c} />
            </Col>
          ))}
        </Row>
      </div>
    </>
  );
};
export async function getStaticProps() {
  const categories = await fetchCategories("8974829147");
  console.log("******** categories : ", categories);

  return {
    props: {
      categories: categories,
    },
  };
}

SanPham.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default SanPham;
