import Head from "next/head";
import Footer from "./footer";

import {
  addressIcon,
  btnPhoneIconTranf,
  supplierAvatarLarge,
  supplierBg,
} from "@/constants/images";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import MainHeader from "./header";

interface IMainLayoutProps {
  children: React.ReactNode;
}
const mapTab = {
  "gioi-thieu-chung": 2,
  "san-pham": 1,
  "[slug]": 0,
};
export default function SupplierLayout({ children }: IMainLayoutProps) {
  const router = useRouter();
  const [currentTab, setCurrentTab] = useState(0);
  useEffect(() => {
    let path = router.pathname.split("/");
    let cTab = 0;
    for (const [key, value] of Object.entries(mapTab)) {
      console.log(`${key}: ${value}`);
      if (path[path.length - 1].includes(key)) {
        cTab = value;
        break;
      }
    }
    setCurrentTab(cTab);
  }, [router]);

  return (
    <>
      <Head>
        <title>IBUILD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="max-w-[1440px] h-auto p-0 m-auto flex flex-col">
        <MainHeader />
        <div className="flex flex-col items-center p-4 lg:px-20 lg:pt-0 lg:py-[60px] isolate">
          <div className="flex flex-col justify-start w-full relative">
            <div className="max-h-[227px] h-auto">
              <Image
                className="max-h-[150px] lg:max-h-full rounded-[4px] lg:rounded-none"
                src={supplierBg}
                alt="bg"
              />
            </div>
            <div className="pl-0 mt-12 lg:pl-[226px] lg:mt-4">
              <div className="w-full flex justify-between items-center flex-col lg:flex-row gap-5 lg:gap-0">
                <div className="flex flex-col-reverse gap-2 lg:flex-col lg:gap-0">
                  <div className="flex justify-start items-center">
                    <div className="w-6 h-6">
                      <Image src={addressIcon} alt="" />
                    </div>
                    <div className="ml-2 font-normal text-base leading-[150%]">
                      158 Nguyễn Khánh Toàn, Quan Hoa, Cầu Giấy, Hà Nội
                    </div>
                  </div>
                  <div className="mb-2">
                    <h3>Trung tâm VLXD Thống nhất</h3>
                  </div>
                </div>
                <div className="max-w-full w-full lg:max-w-[276px]">
                  <button className="btn-in-card view-detail">
                    <Image src={btnPhoneIconTranf} alt="" />
                    0272 387 2233
                  </button>
                </div>
              </div>
            </div>
            <div className="left-[41%] lg:left-[72px] bottom-[152px] lg:bottom-0 w-20 lg:w-[140px] h-20 lg:h-[140px] absolute rounded-[50%]">
              <Image
                src={supplierAvatarLarge}
                alt="bg"
                className="w-20 lg:w-full h-20 lg:h-full"
              />
            </div>
          </div>
          <div className="flex flex-col items-start p-0 w-full">
            <div className="overflow-auto lg:overflow-visible whitespace-nowrap lg:whitespace-normal flex flex-row items-start px-0 pt-10 pb-0 gap-6 mb-10 max-w-full">
              <div
                onClick={() => {
                  router.push({
                    pathname: `/dai-ly/[slug]`,
                    query: {
                      slug: router.query.slug,
                    },
                  });
                }}
                className={`menu-item ${currentTab === 0 ? "active" : ""} `}
              >
                Thông tin nhà cung cấp
                <div className="bottom-menu"></div>
              </div>
              <div
                onClick={() => {
                  router.push({
                    pathname: `/dai-ly/[slug]/san-pham`,
                    query: {
                      ...router.query,
                      tab: "nhom-san-pham",
                    },
                  });
                }}
                className={`menu-item ${currentTab === 1 ? "active" : ""} `}
              >
                Tất cả sản phẩm
                <div className="bottom-menu"></div>
              </div>
              <div
                onClick={() => {
                  router.push({
                    pathname: `/dai-ly/[slug]/gioi-thieu-chung`,
                    query: {
                      slug: router.query.slug,
                    },
                  });
                }}
                className={`menu-item ${currentTab === 2 ? "active" : ""} `}
              >
                Giới thiệu chung
                <div className="bottom-menu"></div>
              </div>
            </div>
            {children}
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}
