import Head from "next/head";
import "../styles/menu.module.scss";
import Script from "next/script";

import Footer from "./footer";

import Link from "next/link";
import MainHeader from "./layouts/header";

interface IMainLayoutProps {
  children: React.ReactNode;
}

export default function MainLayout({ children }: IMainLayoutProps) {
  return (
    <>
      <Head>
        <title>IBUILD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossOrigin="anonymous"
        />
      </Head>
      <div className="wrapper">
        <MainHeader />
        {children}
        <Footer />
        <div
          className="offcanvas offcanvas-end"
          tabIndex={-1}
          id="menuDrawer"
          aria-labelledby="offcanvasNavbarLabel"
        >
          <div className="offcanvas-body">
            <ul className="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li className="nav-item">
                <Link className="nav-link menu-item" href="/san-pham">
                  Sản phẩm
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link menu-item" href="/van-ban-phap-ly">
                  Văn bản pháp lý
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link menu-item" href="/thong-tin-xay-dung">
                  Thông tin xây dựng
                </Link>
              </li>
              <li className="nav-item">
                <span className="sepec-menu">
                  <Link href="/dang-ky" className="nav-link menu-item">
                    Đăng ký{" "}
                  </Link>
                  <span className="spece"> / </span>
                  <Link href="/dang-nhap" className="nav-link menu-item">
                    Đăng nhập
                  </Link>
                </span>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        crossOrigin="anonymous"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      />
    </>
  );
}
