import Head from "next/head";
import "../styles/menu.module.scss";
import Script from "next/script";

import Footer from "./layouts/footer";

import Link from "next/link";
import MainHeader from "./layouts/header";

interface IMainLayoutProps {
  children: React.ReactNode;
}

export default function MainLayout({ children }: IMainLayoutProps) {
  return (
    <>
      <Head>
        <title>IBUILD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="wrapper">
        <MainHeader />
        {children}
        <Footer />
      </div>
    </>
  );
}
