import Head from "next/head";
import "../styles/menu.module.scss"
import Script from "next/script";
import logoImage from '../images/iBuild.svg';
import Image from 'next/image';
import Footer from './footer'
import { menuIcon } from "@/constants/images";

interface IMainLayoutProps {
  children: React.ReactNode;
}
export default function MainLayout({ children }: IMainLayoutProps) {
  return (
    <>
      <Head>
        <title>IBUILD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossOrigin="anonymous"/>
      </Head>
      <div className="wrapper">
        <div className="main-header">
          <a href="#" className="logo">
            <Image src={logoImage} alt="IBUILD" />
          </a>
          <div className="menu">
            <div className="menu-items">
              <a href="./products.html" className="menu-item">
                Sản phẩm
              </a>
              <a href="#" className="menu-item">
                Văn bản pháp lý
              </a>
              <a href="#" className="menu-item">
                Thông tin xây dựng
              </a>
              <span>
                <a href="./sign-up.html" className="menu-item">
                  Đăng ký{" "}
                </a>
                /
                <a href="./sign-in.html" className="menu-item">
                  Đăng nhập
                </a>
              </span>
            </div>
            <div
              className="toggle-button"
              data-bs-toggle="offcanvas"
              data-bs-target="#menuDrawer"
              aria-controls="offcanvasNavbar"
            >
              <Image src={menuIcon} alt="" />
            </div>
          </div>
        </div>
        {children}
        <Footer/>
        <div
          className="offcanvas offcanvas-end"
          tabIndex={-1}
          id="menuDrawer"
          aria-labelledby="offcanvasNavbarLabel"
        >
          <div className="offcanvas-body">
            <ul className="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li className="nav-item">
                <a className="nav-link menu-item" href="#">
                  Sản phẩm
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link menu-item" href="#">
                  Văn bản pháp lý
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link menu-item" href="#">
                  Thông tin xây dựng
                </a>
              </li>
              <li className="nav-item">
                <span className="sepec-menu">
                  <a href="./sign-up.html" className="nav-link menu-item">
                    Đăng ký{" "}
                  </a>
                  <span className="spece"> / </span>
                  <a href="./sign-in.html" className="nav-link menu-item">
                    Đăng nhập
                  </a>
                </span>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      crossOrigin="anonymous" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" />
    </>
  );
}
