export { default as AccountInfo } from './AccountInfo'
export { default as AddressInfo } from './AddressInfo'
export { default as ChangePassword } from './ChangePassword'
export { default as BecomeExpertModal } from './BecomeExpertModal'
export { default as WatchList } from './WatchList'
export { default as WatchListProduct } from './WatchListProduct'
export { default as ChangeSuccess } from './ChangeSuccess'