export { default as allProduct } from './icons/product_types/all_product.svg'
export { default as camera } from './icons/product_types/camera.svg'
export { default as clockSafe } from './icons/product_types/clock_safe.svg'
export { default as fire } from './icons/product_types/fire.svg'
export { default as focusSystem } from './icons/product_types/focus.svg'
export { default as windowSystem } from './icons/product_types/window.svg'

export { default as arrowDown } from './icons/arrow_down.png'
export { default as filterIcon } from './icons/filter_icon.svg'
export { default as filterIconWhite } from './icons/filter_icon_white.svg'