import { ReactElement } from "react";
import MainLayout from "@/components/main-layout";
import { NextPageWithLayout } from "./_app";
import Head from "next/head";
const EmptyPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Empty</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col justify-start px-4 pt-[60px] pb-4">
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </div>
    </>
  );
};
EmptyPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default EmptyPage;
