import { useState, ReactElement } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import useSWR from "swr";

import { NextPageWithLayout } from "./_app";
import {
  MenuDropdown,
  WrapperDesignCard,
  Search,
  WrapperDropdown,
} from "@/components/designs";
import MainLayout from "@/components/main-layout";
import { IDesignSearch } from "@/lib/types";
import { getDesignBySearch } from "@/lib/api/design";
import { Pagination } from "antd";

const DesignsPage: NextPageWithLayout = () => {
  // state
  const [params, setParams] = useState<IDesignSearch>({
    skip: 0,
    limit: 9,
    categoryId: "",
    keyword: "",
  });
  const [paging, setPaging] = useState({
    current: 1,
    total: 0,
  });

  // swr
  const { data: designs, isLoading } = useSWR(params, getDesignBySearch, {
    onSuccess: (data) => {
      console.log(data);
      setPaging((prev) => ({
        ...prev,
        total: data?.paging?.total || 0,
      }));
    },
  });

  // function
  const onChangePagination = (page: number) => {
    setPaging((prev) => ({
      ...prev,
      current: page,
    }));
    setParams((prev) => ({
      ...prev,
      skip: (page - 1) * 9,
    }));
  };

  return (
    <>
      <Head>
        <title>Mẫu thiết kế</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className="flex flex-col justify-start px-4 pt-[60px] pb-4">
        <div className="w-full h-16 relative">
          <Search />
        </div>
        <div className="w-full flex flex-row mt-8 gap-12">
          <div className="w-[230px] custom-menu">
            <WrapperDropdown />
          </div>
          <WrapperDesignCard />
        </div>
        <div className="mt-4">
          <div className="w-full text-center">
            <Pagination
              onChange={onChangePagination}
              current={paging.current}
              pageSize={9}
              total={paging.total}
              hideOnSinglePage
            />
          </div>
        </div>
      </section>
    </>
  );
};
DesignsPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default DesignsPage;
