import { ReactElement } from "react";
import MainLayout from "@/components/main-layout";
import { NextPageWithLayout } from "./_app";
import Head from "next/head";
const DesignsPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Mẫu thiết kế</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="main-content">
        <h1>Mẫu thiết kế</h1>
      </div>
    </>
  );
};
DesignsPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default DesignsPage;
