import Head from "next/head";
import "../styles/menu.module.scss";
import Script from "next/script";

import Footer from "./layouts/footer";

// import Link from "next/link";
import MainHeader from "./layouts/header";
import { RootState, store } from "src/store/store";
import { Provider, useSelector } from "react-redux";
// import { useRouter } from "next/router";
// import { useEffect } from "react";
interface IMainLayoutProps {
  children: React.ReactNode;
}

export default function MainLayout({ children }: IMainLayoutProps) {
  // const unAuthorized = useSelector(
  //   (state: RootState) => state.auth.unAuthorized
  // );

  // const router = useRouter();

  // useEffect(() => {
  //   if (unAuthorized) {
  //     const pathname = router.pathname;
  //     router.push({
  //       pathname: "/dang-nhap",
  //       query: {
  //         redirect: pathname,
  //         ...router.query,
  //       },
  //     });
  //   }
  // }, [unAuthorized, router]);

  return (
    <>
      <Head>
        <title>IBUILD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Provider store={store}>
        <div className="max-w-[1440px] flex flex-col m-auto p-0 h-auto">
          <MainHeader />
          {children}
          <Footer />
        </div>
      </Provider>
    </>
  );
}
