import { ReactElement } from "react";
import MainLayout from "../components/main-layout";
import { NextPageWithLayout } from "./_app";
import Head from "next/head";
import style from "@/styles/modules/supplier.module.scss";
import Image from "next/image";
import {
  addressIcon,
  btnPhoneIconTranf,
  supplierAvatarLarge,
  supplierBg,
} from "@/constants/images";
import Link from "next/link";
import SupplierChart from "@/components/supplier/supplier-chart";
const SupplierPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Đại lý</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={style.supplierMain}>
        <div className={style.supplierHeader}>
          <div className={style.supplierBackground}>
            <Image
              className={style.supplierBackgroundImage}
              src={supplierBg}
              alt="bg"
            />
          </div>
          <div className={style.supplierInfo}>
            <div className={style.supplierInfoDetail}>
              <div className={style.supplierInfoDetailName}>
                <div className={style.supplierAddress}>
                  <div className={style.supplierAddressIcon}>
                    <Image src={addressIcon} alt="" />
                  </div>
                  <div className={style.supplierAddressText}>
                    158 Nguyễn Khánh Toàn, Quan Hoa, Cầu Giấy, Hà Nội
                  </div>
                </div>
                <div className={style.supplierTitle}>
                  <h3>Trung tâm VLXD Thống nhất</h3>
                </div>
              </div>
              <div className={style.supplierInfoDetailAction}>
                <button
                  // onClick={() => {
                  //   handleClickProduct(supplier.id);
                  // }}
                  className="btn-in-card view-detail"
                >
                  <Image src={btnPhoneIconTranf} alt="" />
                  0272 387 2233
                </button>
              </div>
            </div>
          </div>
          <div className={style.supplierAvatar}>
            <Image src={supplierAvatarLarge} alt="bg" />
          </div>
        </div>
        <div className={style.supplierContainer}>
          <div className={style.supplierHeaderMenu}>
            <Link href="/" className="menu-item active">
              Thông tin nhà cung cấp
              <div className="bottom-menu"></div>
            </Link>
            <Link href="/" className="menu-item">
              Tất cả sản phẩm
              <div className="bottom-menu"></div>
            </Link>
            <Link href="/" className="menu-item">
              Giới thiệu chung
              <div className="bottom-menu"></div>
            </Link>
          </div>
          <div className={style.supplierHeaderContent}>
            <SupplierChart />
          </div>
        </div>
      </div>
    </>
  );
};
SupplierPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default SupplierPage;
