import { ReactElement } from "react";
import MainLayout from "@/components/main-layout";
import { NextPageWithLayout } from "./_app";
import Head from "next/head";
import { Skeleton } from "antd";
const EmptyPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Empty</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="main-content">
        <h1>Empty</h1>
        <div>
          <Skeleton active />
          <Skeleton />
          <Skeleton />
        </div>
      </div>
    </>
  );
};
EmptyPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default EmptyPage;
