import { ReactElement } from "react";
import MainLayout from "../components/main-layout";
import { NextPageWithLayout } from "./_app";
import Head from "next/head";
import style from "@/styles/modules/build-info.module.scss";
import { Row, Col } from "antd";
import Image from "next/image";
import { news1, rightIcon } from "@/constants/images";
import NewCardFeature from "@/components/news/new-card-feature";
import NewCardNormal from "@/components/news/news-card-normal";
import news from "../data/news1.json";
const ThongTinXayDung: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Thông tin xây dựng</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="main-content">
        <section className={style.Build_Features}>
          <div className={style.Build_Features_Top1}>
            <div className={style.Build_Features_Top1_Image}>
              <Image style={{ width: "100%" }} src={news1} alt="" />
            </div>
            <div className={style.Build_Features_Top1_Title}>
              <div className={style.Build_Features_Top1_Title_Date}>
                25/07/2022
              </div>
              <div className={style.Build_Features_Top1_Title_Title}>
                Triển khai thực hiện Bộ tiêu chí ứng xử trong gia đình đến năm
                2025 trên địa bàn tỉnh Sơn La
              </div>
            </div>
            <div className={style.Build_Features_Top1_Desc}>
              Nullam scelerisque alias nemo repudiandae cupidatat, habitasse
              adipisicing, hendrerit, aliquet, fusce metus dolor libero? Ab,
              viverra dictumst penatibus odio, sodales magnam provident non
              adipiscing adipisicing, laudantium iaculis pede,
            </div>
          </div>
          <div className={style.Build_Features_Top25}>
            <NewCardFeature />
            <NewCardFeature />
            <NewCardFeature />
          </div>
        </section>
        <section className={style.Build_News}>
          <div className={style.New_Section_Title}>
            <div className={style.New_Section_Title_Title}>
              Tin tức & Sự kiện
            </div>
            <div className={style.New_Section_Title_ViewMore}>
              <div className={style.New_Section_Title_ViewMore_Text}>
                Xem tất cả
              </div>
              <Image
                className={style.New_Section_Title_ViewMore_Image}
                src={rightIcon}
                alt=""
              />
            </div>
          </div>
          <div className={style.New_Container}>
            <Row gutter={32}>
              {news.map((n) => (
                <Col key={n.id} lg={6} md={24}>
                  <NewCardNormal news={n} />
                </Col>
              ))}
            </Row>
          </div>
        </section>
        <section className={style.Build_Administrative}>
          <div className={style.New_Section_Title}>
            <div className={style.New_Section_Title_Title}>
              Cải cách hành chính
            </div>
            <div className={style.New_Section_Title_ViewMore}>
              <div className={style.New_Section_Title_ViewMore_Text}>
                Xem tất cả
              </div>
              <Image
                className={style.New_Section_Title_ViewMore_Image}
                src={rightIcon}
                alt=""
              />
            </div>
          </div>
          <div className={style.New_Container}>
            <Row gutter={32}>
              {news.map((n) => (
                <Col key={n.id} lg={6} md={24}>
                  <NewCardNormal news={n} />
                </Col>
              ))}
            </Row>
          </div>
        </section>
      </div>
    </>
  );
};
ThongTinXayDung.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default ThongTinXayDung;
