import Head from "next/head";
import Footer from "./footer";

import MainHeader from "./header";
import style from "@/styles/modules/supplier.module.scss";
import {
  addressIcon,
  btnPhoneIconTranf,
  supplierAvatarLarge,
  supplierBg,
} from "@/constants/images";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";

interface IMainLayoutProps {
  children: React.ReactNode;
}
const mapTab = {
  "gioi-thieu-chung": 2,
  "san-pham": 1,
  "[slug]": 0,
};
export default function SupplierLayout({ children }: IMainLayoutProps) {
  const router = useRouter();
  const [currentTab, setCurrentTab] = useState(0);
  useEffect(() => {
    let path = router.pathname.split("/");
    let cTab = 0;
    for (const [key, value] of Object.entries(mapTab)) {
      console.log(`${key}: ${value}`);
      if (path[path.length - 1].includes(key)) {
        cTab = value;
        break;
      }
    }
    setCurrentTab(cTab);
  }, [router]);

  return (
    <>
      <Head>
        <title>IBUILD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="wrapper">
        <MainHeader />
        <div className={style.supplierMain}>
          <div className={style.supplierHeader}>
            <div className={style.supplierBackground}>
              <Image
                className={style.supplierBackgroundImage}
                src={supplierBg}
                alt="bg"
              />
            </div>
            <div className={style.supplierInfo}>
              <div className={style.supplierInfoDetail}>
                <div className={style.supplierInfoDetailName}>
                  <div className={style.supplierAddress}>
                    <div className={style.supplierAddressIcon}>
                      <Image src={addressIcon} alt="" />
                    </div>
                    <div className={style.supplierAddressText}>
                      158 Nguyễn Khánh Toàn, Quan Hoa, Cầu Giấy, Hà Nội
                    </div>
                  </div>
                  <div className={style.supplierTitle}>
                    <h3>Trung tâm VLXD Thống nhất</h3>
                  </div>
                </div>
                <div className={style.supplierInfoDetailAction}>
                  <button
                    // onClick={() => {
                    //   handleClickProduct(supplier.id);
                    // }}
                    className="btn-in-card view-detail"
                  >
                    <Image src={btnPhoneIconTranf} alt="" />
                    0272 387 2233
                  </button>
                </div>
              </div>
            </div>
            <div className={style.supplierAvatar}>
              <Image src={supplierAvatarLarge} alt="bg" />
            </div>
          </div>
          <div className={style.supplierContainer}>
            <div className={style.supplierHeaderMenu}>
              <div
                onClick={() => {
                  router.push({
                    pathname: `/dai-ly/[slug]`,
                    query: {
                      slug: router.query.slug,
                    },
                  });
                }}
                className={`menu-item ${currentTab === 0 ? "active" : ""} `}
              >
                Thông tin nhà cung cấp
                <div className="bottom-menu"></div>
              </div>
              <div
                onClick={() => {
                  router.push({
                    pathname: `/dai-ly/[slug]/san-pham`,
                    query: {
                      ...router.query,
                      tab: "nhom-san-pham",
                    },
                  });
                }}
                className={`menu-item ${currentTab === 1 ? "active" : ""} `}
              >
                Tất cả sản phẩm
                <div className="bottom-menu"></div>
              </div>
              <div
                onClick={() => {
                  router.push({
                    pathname: `/dai-ly/[slug]/gioi-thieu-chung`,
                    query: {
                      slug: router.query.slug,
                    },
                  });
                }}
                className={`menu-item ${currentTab === 2 ? "active" : ""} `}
              >
                Giới thiệu chung
                <div className="bottom-menu"></div>
              </div>
            </div>
            {children}
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}
