import { Col, Row } from "antd";
import { ReactElement, useState, useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";

import MainLayout from "@/components/main-layout";
import NewCardFeature from "@/components/news/new-card-feature";
import NewCardNormal from "@/components/news/news-card-normal";
import { news1 } from "@/constants/images";
import { NextPageWithLayout } from "../_app";

import {
  fetchNewsForHome,
  getNewByCategoryId,
  listNewCategories,
} from "src/lib/api/news";
import { INews } from "src/lib/types";
import useSWR from "swr";
import NewCardLoading from "@/components/news/NewCardLoading";

const ThongTinXayDung: NextPageWithLayout = () => {
  const router = useRouter();
  const { query } = router;
  const { categoryName } = query;

  // state
  const [currentCategory, setCurrentCategory] = useState("");
  const [params, setParams] = useState({
    skip: 0,
    limit: 8,
    categoryId: "",
  });
  const [totalNew, setTotalNew] = useState(0);

  // api
  const { data, error } = useSWR<INews[], []>("news", fetchNewsForHome, {
    fallbackData: [],
  });
  const { data: newCategories } = useSWR("category", listNewCategories);
  const { data: news, isLoading: loadingNew } = useSWR(
    params,
    getNewByCategoryId,
    {
      onSuccess: (data) => {
        if (data) {
          setTotalNew(data.paging.total);
        }
      },
    }
  );
  console.log(news);

  // function
  const handleClickCategory = (slug: string) => {
    console.log(slug);
    router.push({
      pathname: router.pathname,
      query: {
        ...router.query,
        categoryName: slug,
      },
    });
  };

  useEffect(() => {
    if (categoryName) {
      setCurrentCategory(categoryName as string);
      const option = newCategories?.find((ca) => ca.slug === categoryName);
      option &&
        setParams((prev) => ({
          ...prev,
          categoryId: option.id,
        }));
    } else if (data) {
      setCurrentCategory(data[0]?.slug);
    }
  }, [categoryName, data, newCategories]);

  if (!data) {
    return <div>error</div>;
  }
  return (
    <>
      <Head>
        <title>Thông tin xây dựng</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col justify-start px-4 pt-[60px] pb-0">
        <section className="flex flex-col lg:flex-row justify-start p-0 gap-8 w-full">
          <div className="flex-1 flex flex-col items-start p-0 gap-6">
            <div className="rounded-[4px] w-full">
              <Image className="w-full" src={news1} alt="" />
            </div>
            <div className="flex flex-col items-start p-0">
              <div className="text-[14px] font-medium leading-[150%] text-[#717171]">
                25/07/2022
              </div>
              <div className="text-2xl font-medium not-italic leading-[150%]">
                Triển khai thực hiện Bộ tiêu chí ứng xử trong gia đình đến năm
                2025 trên địa bàn tỉnh Sơn La
              </div>
            </div>
            <div className="text-base font-normal leading-[150%] text-[#717171]">
              Nullam scelerisque alias nemo repudiandae cupidatat, habitasse
              adipisicing, hendrerit, aliquet, fusce metus dolor libero? Ab,
              viverra dictumst penatibus odio, sodales magnam provident non
              adipiscing adipisicing, laudantium iaculis pede, f
            </div>
          </div>
          <div className="flex-1 flex flex-col items-start p-0 gap-8">
            <NewCardFeature />
            <NewCardFeature />
            <NewCardFeature />
          </div>
        </section>
        <section className="mt-[60px]">
          <div className="flex flex-row gap-4 items-center mb-8">
            {newCategories &&
              newCategories?.length > 0 &&
              newCategories.map((category) => (
                <div
                  key={category.id}
                  className={`text-2xl cursor-pointer ${
                    currentCategory === category.slug
                      ? "new-category text-primary-color"
                      : "text-[#666666]"
                  }`}
                  onClick={() => handleClickCategory(category.slug)}
                >
                  {category.name}
                </div>
              ))}
          </div>
          <div>
            <Row gutter={[32, 32]}>
              {!loadingNew &&
                news &&
                news.data?.length > 0 &&
                news.data.map((n) => (
                  <Col key={n.id} lg={6} md={24}>
                    <NewCardNormal news={n} />
                  </Col>
                ))}

              {loadingNew &&
                Array(8)
                  .fill(0)
                  .map((n, idx) => (
                    <Col key={n.id} lg={6} md={24}>
                      <NewCardLoading key={idx} />
                    </Col>
                  ))}
            </Row>
          </div>
        </section>
        {totalNew > 8 && (
          <section className="mt-8 mb-16 text-center">
            <button className="text-white font-medium text-base h-[46px] w-[150px] rounded bg-primary-color">
              Xem tất cả
            </button>
          </section>
        )}
      </div>
    </>
  );
};
export async function getStaticProps() {
  // `getStaticProps` is executed on the server side.
  const newss = await fetchNewsForHome("/news");
  return {
    props: {
      newss: newss,
    },
  };
}

ThongTinXayDung.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default ThongTinXayDung;
