name: Deployment Workflow
on:
  push:
    branches: [staging]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: - install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/ibuild/frontend  && git pull && exit"
      - name: install packages and clear build cache
        script: | 
          cd /home/ibuild/frontend
          npm install
          rm -rf .next
      - name: build
        script: | 
          cd /home/ibuild/frontend
          npm run build
      - name: deploy with pm2
        script: | 
          pm2 restart all
