import { ReactElement } from "react";
import MainLayout from "@/components/main-layout";
import { NextPageWithLayout } from "../../_app";
import Head from "next/head";
import { ParsedUrlQuery } from "querystring";
import useSWR from "swr";
import { useRouter } from "next/router";
import {
  GetServerSidePropsContext,
  GetStaticPaths,
  GetStaticPropsContext,
} from "next";
import {
  fetchNewCategories,
  fetchNewCategoryBySlug,
  fetchNewDefault,
} from "lib/api/news";
import { INewCategory } from "lib/types";
interface IParams extends ParsedUrlQuery {
  cslug: string;
}

const NewCategories: NextPageWithLayout = () => {
  const { query } = useRouter();

  return (
    <>
      <Head>
        <title>Empty</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="main-content">
        <h1>Empty</h1>
      </div>
    </>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { cslug } = context.params as IParams;
  const news = await fetchNewCategoryBySlug(cslug);

  if (!news) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      news,
    },
  };
}
NewCategories.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default NewCategories;
