import { ReactElement } from "react";
import MainLayout from "@/components/main-layout";
import { NextPageWithLayout } from "../../_app";
import Head from "next/head";
import { ParsedUrlQuery } from "querystring";
import useSWR from "swr";
import { useRouter } from "next/router";
import { GetServerSidePropsContext } from "next";
import { fetchNewCategoryBySlug } from "lib/api/news";
import style from "@/styles/modules/build-info.module.scss";
import Breadcrums from "@/components/common/breadcrums";
import { Col, Pagination, Row } from "antd";
import NewCardNormal from "@/components/news/news-card-normal";
import newss from "@/data/news1.json";
interface IParams extends ParsedUrlQuery {
  cslug: string;
}

const NewCategories: NextPageWithLayout = () => {
  const { query } = useRouter();
  const { data, error } = useSWR(query.cslug, fetchNewCategoryBySlug);
  if (!data) {
    return <div>error</div>;
  }
  const cate = data;
  const breadcrumbs = [
    {
      title: "Thông tin xây dựng",
      slug: "thong-tin-xay-dung",
    },
    {
      slug: "",
      title: cate?.name || "",
    },
  ];
  return (
    <>
      <Head>
        <title>{cate?.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={style.NewsCategoryMain}>
        <Breadcrums breadcrumbs={breadcrumbs} />
        <div className={style.New_Container}>
          <Row gutter={[32, 32]}>
            {newss.map((n) => (
              <Col key={n.id} lg={6} md={24}>
                <NewCardNormal news={n} />
              </Col>
            ))}
          </Row>
        </div>
      </div>
      <div className={style.NewsPagination}>
        <Pagination total={50} current={1} pageSize={10} />
      </div>
    </>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { cslug } = context.params as IParams;
  const cate = await fetchNewCategoryBySlug(cslug);

  if (!cate) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      cate,
    },
  };
}
NewCategories.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
export default NewCategories;
